[package]
name = "botw-recipe-wmcdb"
description = "BOTW recipe database for WMC"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
enum-map = "2.7.3"
enumset = "1.1.5"
fs2 = "0.4.3"
log = "0.4.22"
rand = "0.8.5"

static_assertions = "1.1.0"

# DB dependencies
serde = { version = "1.0.215", features = ["derive"] }
serde_yaml_ng = "0.10.0"
thiserror = "1.0.69"
sha2 = "0.10.8"
derivative = "2.2.0"
base16ct = { version = "0.2.0", features = ["std"] }

ts-rs = { version = "9.0.1", optional = true }

[dependencies.botw-recipe-cook]
path = "../cook"
features = ["wmcdb"]

[dependencies.botw-recipe-sys]
path = "../generated"
features = [
    "prompt-entanglement",
]

[features]
__ts-binding = ["dep:ts-rs"] # internal: enable ts-rs to generate bindings
