[workspace]
members = [
    "packages/app/src-tauri", 
    "packages/cook",
    "packages/cook-cli",
    "packages/wmcdb",
    "packages/data-utils",
    "packages/generated",
    "packages/searcher-tauri",
    "research", 
]
resolver = "2"
