version: '3'

env:
  CONSOLE_ADDR: 192.168.0.161:5000 # can be overriden in .env
dotenv: [".env"]

includes:
  # BOTW RDB App
  rdb:
    taskfile: ./app/rdb
    dir: ./app/rdb

  # Recipe Dumper Mod
  console:
    taskfile: ./dump/console
    dir: ./dump/console

  # Recipe Dumper and Verifier
  dump:
    taskfile: ./dump/emulate
    dir: ./dump/emulate

tasks:
  research:
    desc: Reproduce research
    dir: research
    cmds:
    - python main.py {{.CLI_ARGS}}


  check:
    vars:
      CLIPPY_FLAGS: -D warnings -D clippy::todo
    cmds:
    - cargo clippy --package botw-recipe-data --all-targets -- {{.CLIPPY_FLAGS}}
    - cargo clippy --package botw-recipe-dump-emulate --all-targets -- {{.CLIPPY_FLAGS}}
    - cargo clippy --package botw-recipe-database --all-targets -- {{.CLIPPY_FLAGS}}
    - cargo fmt --check

  fix:
    desc: Fix code issues in .rs
    cmds:
    - cargo fmt --all
