[package]
name = "research"
description = "research scripts"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
crc = "3.2.1"
itertools = "0.13.0"
num_cpus = "1.16.0"
threadpool = "1.8.1"

[[bin]]
name = "bfcrc32"
path = "bfcrc32.rs"
