// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cooking-related errors
 */
export type CookError =
    | { type: "Yaml"; data: string }
    | { type: "ReadIngr"; data: Array<CookError> }
    | { type: "ReadRecipe"; data: string }
    | { type: "ItemNotFound"; data: string }
    | { type: "AmbiguousIngr"; data: [string, Array<string>] }
    | { type: "TooManyIngr" }
    | { type: "TooFewIngr" }
    | { type: "InvalidRecipeId"; data: number }
    | { type: "Data"; data: string };
