// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CookError } from "./CookError";

/**
 * Database-related errors
 */
export type DatabaseError =
    | { type: "IO"; data: string }
    | { type: "YAML"; data: string }
    | { type: "Cooking"; data: CookError }
    | { type: "Locked" }
    | { type: "MissingIndex" }
    | { type: "InvalidIndexChunkCount"; data: [number, number] }
    | { type: "MissingChunk"; data: number }
    | { type: "InvalidChunkSize"; data: [number, number] }
    | { type: "InvalidRecipeId"; data: number }
    | { type: "TooManyTemporary" };
