// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DatabaseError } from "./DatabaseError";

export type Error =
    | { type: "IOError"; data: string }
    | { type: "PoisonError"; data: string }
    | { type: "ExecutorUnavailable" }
    | { type: "Aborted" }
    | { type: "DatabaseError"; data: DatabaseError }
    | { type: "MissingSearchResult" }
    | { type: "Generic"; data: string };
