// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OptimizedRecipeData = {
    actors: Array<Array<number>>;
    value: number;
    isHearty: boolean;
    price: number;
};
