// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for the `search-complete` event
 */
export type SearchComplete = {
    /**
     * Number of recipes found
     */
    foundCount: number;
    /**
     * Actors in those recipes
     *
     * Position corresponds to actor id, value to the number of recipes.
     * Search may not provide actor details if there are too many results
     */
    actors: Array<number> | null;
};
