// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WeaponModifierSet } from "./WeaponModifierSet";

/**
 * Filter for records
 */
export type SearchFilter = {
    minValue: number;
    maxValue: number;
    includesModifier: WeaponModifierSet;
    excludesModifier: WeaponModifierSet;
    includeCritRngHp: boolean;
    includePeOnly: boolean;
};
