[package]
name = "botwrdb"
version = "0.2.0"
description = "BotW WMC Recipe Searcher App"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies.botw-recipe-searcher-tauri]
path = "../../searcher-tauri"

[dependencies]
tauri = { version = "1", features = [ "shell-open"] }
log = "0.4.22"
env_logger = "0.11.5"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
devtools = ["tauri/devtools"]
