[module]
name = "botwrdump"
title-id = 0x01007ef00011e000

[build]
sources = [
    "src",
    "libs/botw-symbols/src",
]
includes = [
    "libs/botw/src",
    "libs/botw/lib/sead/include",
    "libs/botw/lib/NintendoSDK/include",
    "libs/botw-symbols/include",
]
ldscripts = [
    "libs/botw-symbols/ld/ld150.ld",
]

[build.flags]
c = [
    "<default>",
    "-DNNSDK",
    "-DSWITCH",
    "-D__SWITCH__",
    "-DNN_SDK_MAJOR=4",
    "-DNN_SDK_MINOR=4",
    "-DNN_SDK_PATCH=0",
    "-DNN_WARE_MAJOR=4",
    "-DNN_WARE_MINOR=4",
    "-DNN_WARE_PATCH=0",
    "-DBOTW_VERSION=150",
]
cxx = [
    "<default>",
    "-Wno-invalid-offsetof",
        # "-Wno-strict-aliasing",
]

[check]
symbols = [
    "libs/botw-symbols/symbols/150/main.syms",
    "libs/botw-symbols/symbols/150/rtld.syms",
    "libs/botw-symbols/symbols/150/sdk.syms",
    "libs/botw-symbols/symbols/150/subsdk0.syms",
]
