[package]
name = "botw-recipe-searcher-tauri"
version = "0.1.0"
edition = "2021"
description = "WMC recipe searcher and tauri app"

[dependencies]
enum-map = "2.7.3"
enumset = "1.1.5"
log = "0.4.25"
num_cpus = "1.16.0"
oneshot = { version = "0.1.8", default-features = false, features = ["std"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
serde_yaml_ng = "0.10.0"
tauri = { version = "1", features = ["shell-open"] }
thiserror = "2.0.11"
threadpool = "1.8.1"
ts-rs = { version = "9.0.1", optional = true }

[dependencies.botw-recipe-wmcdb]
path = "../wmcdb"

[dependencies.botw-recipe-cook]
path = "../cook"

[dependencies.botw-recipe-sys]
path = "../generated"
features = [
    "actor-enum-map",
]

[features]
__ts-binding = ["dep:ts-rs"] # internal: enable ts-rs to generate bindings
