version: '3'

tasks:
  install:
    desc: Install JS dependencies
    cmds:
    - deno install

  install-ci:
    cmds:
    - deno install --frozen

  dev:
    desc: Run RDB in dev (watch) mode
    env:
      RUST_LOG: info
      BOTWRDB_CONFIG_PATH: ../../../app/rdb/rdb.config.yaml
    cmds:
    - npx tauri dev --features devtools {{.CLI_ARGS}}

  build:
    desc: Build RDB (release) binary
    cmds:
    - npx tauri build {{.CLI_ARGS}}

  dev-js:
    cmds:
    - npx vite

  build-js:
    cmds:
    - node scripts/verifyI18n.cjs
    - npx vite build

  ts-rs:
    desc: Generate TypeScript bindings
    dir: .
    cmds:
    - coreutils rm -rf ../data/bindings
    - coreutils rm -rf src-tauri/bindings
    - coreutils rm -rf src/host/types
    - coreutils mkdir -p src/host/types
    - cargo test --package botw-recipe-data --lib
    - cargo test --package botw-recipe-database
    - coreutils cp -r ../data/bindings/*.ts src/host/types/
    - coreutils cp -r src-tauri/bindings/*.ts src/host/types/
    - npx prettier "./src/host/types/*.ts" --write

  test:
    desc: Run tests
    cmds:
    - npx jest

  check:
    desc: Check for linting and formatting issues in TS code
    aliases: [lint]
    cmds:
    - task: eslint
      vars:
        ESLINT_ARGS: ""
    - task: prettier
      vars:
        PRETTIER_ARGS: --check
    - npx tsc --build
  
  fix:
    desc: Fix linting and formatting issues in TS code
    cmds:
    - task: prettier
      vars:
        PRETTIER_ARGS: --write

  prettier:
    cmds:
    - npx prettier "./**/*.{ts,tsx,json,js,mjs,cjs,css}" {{.PRETTIER_ARGS}}

  eslint:
    cmds:
    - npx eslint src --report-unused-disable-directives --max-warnings 0 --cache {{.ESLINT_ARGS}}
